apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-production
  namespace: argocd
spec:
  project: default
  source:
    path: k8s/python-production
    repoURL: https://github.com/inerplat/fastcampus-devops-testcode-example.git
    ## 레포의 Branch 현재는 main
    targetRevision: main
  destination:
    namespace: python
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

